In [1]:
import numpy as np


In [3]:
x=np.array([1,2,3,4,5,6])
print(x)

[1 2 3 4 5 6]


In [4]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [5]:
x=np.zeros([5])
print(x)

[0. 0. 0. 0. 0.]


In [6]:
x=np.ones([5])
print(x)

[1. 1. 1. 1. 1.]


In [9]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1,2,3],[4,5,6]])
z=x+y
print(z)

[[ 2  4  6]
 [ 8 10 12]]


In [10]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1,2,3],[4,5,6]])
z=x*y
print(z)

[[ 1  4  9]
 [16 25 36]]


In [12]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([1,2,3])
z=np.dot(x,y)
print(z)

[14 32]
